name: Build Pelican site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Theme
        run: pelican-themes -i ../pelican-sober
        working-directory: ./blog
      - name: Render site
        run: pelican content -s publishconf.py
        working-directory: ./blog
      - name: Upload rendered site
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: blog/output
